#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
compose_file="$script_dir/docker-compose.yml"
outputs_file="$script_dir/localstack/outputs.json"
env_file="$script_dir/localstack.env"
localstack_port="${LOCALSTACK_PORT:-4566}"
wiremock_port="${WIREMOCK_PORT:-8080}"

compose() {
  docker compose -f "$compose_file" "$@"
}

require_docker() {
  if ! docker info >/dev/null 2>&1; then
    echo "Docker is not running. Start Docker and retry." >&2
    exit 1
  fi
}

wait_for_url() {
  local name="$1"
  local url="$2"
  local attempts="$3"
  local attempt
  for ((attempt = 1; attempt <= attempts; attempt++)); do
    if curl -fsS "$url" >/dev/null 2>&1; then
      echo "$name is ready."
      return 0
    fi
    sleep 2
  done
  echo "$name did not become ready: $url" >&2
  return 1
}

generate_env() {
  if [[ ! -s "$outputs_file" ]]; then
    echo "Terraform did not produce $outputs_file" >&2
    exit 1
  fi

  {
    echo "# Generated by testing/bootstrap.sh. Do not commit."
    echo "export AWS_ACCESS_KEY_ID=test"
    echo "export AWS_SECRET_ACCESS_KEY=test"
    echo "export AWS_REGION=us-east-1"
    echo "export AWS_DEFAULT_REGION=us-east-1"
    echo "export AWS_EC2_METADATA_DISABLED=true"
    echo "export AWS_ENDPOINT_URL=http://localhost:${localstack_port}"
    echo "export AWS_S3_FORCE_PATH_STYLE=true"
    jq -r --arg endpoint "http://localhost:${localstack_port}" '
      .test_environment.value
      | to_entries[]
      | .value = (if (.value | type) == "string" then (.value | gsub("http://localstack:4566"; $endpoint)) else .value end)
      | "export \(.key)=\(.value | @sh)"
    ' "$outputs_file"
    echo "export WIREMOCK_BASE_URL=http://localhost:${wiremock_port}"
    echo "export DEFAULT_AGENT_DRIVER=mock"
    echo "export DEFAULT_EXECUTION_BACKEND=microvm"
    echo "export DEFAULT_DELIVERY_DESTINATIONS=source"
    echo "export ALLOWED_REPOSITORY_HOSTS=github.com,gitlab.com"
    echo "export ALLOWED_SANDBOX_MODES=read-only,workspace-write"
    echo "export WORKSPACE_ROOT=/tmp/indubitably-agent-runtime-localstack"
    echo "export LOCALSTACK_E2E=true"
  } > "$env_file"
  chmod 600 "$env_file"
}

start() {
  require_docker
  echo "Starting LocalStack and WireMock..."
  compose up -d localstack wiremock
  wait_for_url "LocalStack" "http://localhost:${localstack_port}/_localstack/health" 45
  wait_for_url "WireMock" "http://localhost:${wiremock_port}/__admin/health" 30

  local attempt
  for attempt in 1 2 3; do
    echo "Applying local test infrastructure (attempt ${attempt}/3)..."
    if compose run --rm terraform-init; then
      generate_env
      echo "LocalStack workflow environment is ready."
      echo "Run: source testing/localstack.env"
      return 0
    fi
    if [[ "$attempt" == "3" ]]; then
      echo "Terraform failed after three attempts." >&2
      compose logs localstack >&2 || true
      exit 1
    fi
    sleep 2
  done
}

down() {
  require_docker
  compose down -v --remove-orphans
  rm -f "$env_file" "$outputs_file"
  echo "LocalStack workflow environment removed."
}

status() {
  require_docker
  compose ps
  echo
  curl -fsS "http://localhost:${localstack_port}/_localstack/health" | jq .
}

case "${1:-}" in
  --down|-d)
    down
    ;;
  --reset|-r)
    down
    start
    ;;
  --status|-s)
    status
    ;;
  --print-env)
    [[ -s "$env_file" ]] || { echo "$env_file does not exist; run bootstrap first." >&2; exit 1; }
    cat "$env_file"
    ;;
  --help|-h)
    echo "Usage: ./testing/bootstrap.sh [--down|--reset|--status|--print-env]"
    ;;
  "")
    start
    ;;
  *)
    echo "Unknown option: $1" >&2
    exit 2
    ;;
esac
