import { describe, expect, it } from 'vitest';
import { MAX_ARTIFACT_FILES } from '../../src/domain/artifacts.js';
import {
  publicationManifest,
  validatePublicationPlan,
  type PublicationPlan,
} from '../../src/core/publication-planning.js';
import { sourceFile } from './publication-fixtures.js';

const spec = { version: '1', kind: 'site' } as const;

function plan(): PublicationPlan {
  return {
    kind: 'site', entrypoint: 'index.html',
    files: [{ source: 'generated', path: 'index.html', bytes: new Uint8Array(), mediaType: 'text/html' }],
  };
}

describe('publication plan validation', () => {
  it('accepts empty generated bytes and compares the whole source blob by value', () => {
    const source = sourceFile('source.txt', 'text/plain');
    source.blob.size = 0;
    const value = plan();
    value.files.push({ source: 'blob', path: 'file.txt', blob: { ...source.blob } });
    expect(() => validatePublicationPlan(value, spec, [source])).not.toThrow();
    const selected = value.files[1]!;
    if (selected.source !== 'blob') throw new Error('expected source');
    selected.blob.mediaType = 'application/octet-stream';
    expect(() => validatePublicationPlan(value, spec, [source])).toThrow('unknown source blob');
  });

  it.each([
    ['../escape.txt', 'invalid_path'],
    ['_rat', 'invalid_path'],
    ['_rat/manifest.json', 'invalid_path'],
    ['index.html', 'path_collision'],
  ])('rejects %s before inspecting its invalid blob', (path, code) => {
    const value = plan();
    value.files.push({ source: 'blob', path, blob: { ...sourceFile('x', 'text/plain').blob, size: -1 } });
    expect(() => validatePublicationPlan(value, spec, [])).toThrow(expect.objectContaining({ code }));
  });

  it('rejects an oversized plan before inspecting its paths', () => {
    const value = plan();
    value.files = Array.from({ length: MAX_ARTIFACT_FILES + 1 }, () => ({
      source: 'generated', path: '../invalid', bytes: new Uint8Array(), mediaType: '',
    }));
    expect(() => validatePublicationPlan(value, spec, [])).toThrow(`exceeds ${MAX_ARTIFACT_FILES} files`);
  });

  it('requires both the entrypoint and an explicitly specified primary path', () => {
    const value = plan();
    value.files[0]!.path = 'other.html';
    expect(() => validatePublicationPlan(value, spec, [])).toThrow('does not contain its entrypoint');
    value.files[0]!.path = 'index.html';
    value.primaryPath = '';
    expect(() => validatePublicationPlan(value, spec, [])).toThrow('does not contain its primary path');
  });

  it('rejects invalid generated media types', () => {
    const value = plan();
    value.files = [{ source: 'generated', path: 'index.html', bytes: new Uint8Array(), mediaType: 'text/html\r\nx: y' }];
    expect(() => validatePublicationPlan(value, spec, [])).toThrow('invalid generated bytes');
  });
});

describe('publication manifest projection', () => {
  it('sorts a new file array and takes provenance from explicit values', () => {
    const files = Object.freeze([
      Object.freeze(sourceFile('z.txt', 'text/plain')),
      Object.freeze(sourceFile('index.html', 'text/html')),
    ]);
    const result = publicationManifest({
      publicationId: 'a'.repeat(24), plan: plan(), files,
      runId: 'run-1', conversationId: 'conversation-1', builder: 'custom',
      createdAt: '2026-08-15T00:00:00.000Z',
    });
    expect(result.files.map((file) => file.path)).toEqual(['index.html', 'z.txt']);
    expect(files.map((file) => file.path)).toEqual(['z.txt', 'index.html']);
    expect(result.files[0]).toBe(files[1]);
    expect(result.provenance).toEqual({
      runId: 'run-1', conversationId: 'conversation-1', builder: 'custom',
      createdAt: '2026-08-15T00:00:00.000Z',
    });
    expect(result).not.toHaveProperty('primaryPath');
  });

  it('validates materialized references and never substitutes a timestamp', () => {
    const input = {
      publicationId: 'a'.repeat(24), plan: plan(), files: [sourceFile('index.html', 'text/html')],
      runId: 'run-1', conversationId: '', builder: 'custom', createdAt: '',
    };
    expect(() => publicationManifest(input)).toThrow('provenance is invalid');
    input.createdAt = '2026-08-15T00:00:00.000Z';
    expect(publicationManifest(input).provenance).not.toHaveProperty('conversationId');
    input.files[0]!.blob.size = -1;
    expect(() => publicationManifest(input)).toThrow('invalid blob reference');
  });
});
