import { MAX_ARTIFACT_FILES, validateArtifactPath } from '../domain/artifacts.js';
import type {
  BlobReference,
  PublicationFile,
  PublicationKind,
  PublicationManifest,
  PublicationSpec,
} from '../domain/publications.js';
import {
  PublicationError,
  validateBlobReference,
  validatePublicationManifest,
} from '../domain/publications.js';

export interface PublicationSourceFile {
  path: string;
  blob: BlobReference;
}

export type PlannedPublicationFile =
  | {
      source: 'blob';
      path: string;
      blob: BlobReference;
    }
  | {
      source: 'generated';
      path: string;
      bytes: Uint8Array;
      mediaType: string;
    };

export interface PublicationPlan {
  kind: PublicationKind;
  entrypoint: 'index.html';
  primaryPath?: string;
  files: PlannedPublicationFile[];
}

export function validatePublicationPlan(
  plan: PublicationPlan,
  spec: PublicationSpec,
  sources: readonly PublicationSourceFile[],
): void {
  if (plan.kind !== spec.kind || plan.entrypoint !== 'index.html' || plan.files.length === 0) {
    throw new PublicationError('invalid_request', 'publication builder returned an invalid plan');
  }
  if (plan.files.length > MAX_ARTIFACT_FILES) {
    throw new PublicationError('invalid_request', `publication exceeds ${MAX_ARTIFACT_FILES} files`);
  }
  const paths = new Set<string>();
  const sourceBlobs = new Set(sources.map((source) => blobIdentity(source.blob)));
  for (const file of plan.files) {
    try {
      validateArtifactPath(file.path);
    } catch (error) {
      throw new PublicationError(
        'invalid_path',
        `publication builder returned invalid path ${JSON.stringify(file.path)}`,
        error instanceof Error ? { cause: error } : undefined,
      );
    }
    if (file.path === '_rat' || file.path.startsWith('_rat/')) {
      throw new PublicationError(
        'invalid_path',
        `publication path ${file.path} uses the reserved _rat namespace`,
      );
    }
    if (paths.has(file.path)) {
      throw new PublicationError('path_collision', `duplicate publication path ${file.path}`);
    }
    paths.add(file.path);
    if (file.source === 'blob') {
      validateBlobReference(file.blob);
      if (!sourceBlobs.has(blobIdentity(file.blob))) {
        throw new PublicationError('invalid_request', 'publication builder selected an unknown source blob');
      }
    } else if (
      !(file.bytes instanceof Uint8Array) ||
      typeof file.mediaType !== 'string' ||
      !file.mediaType ||
      file.mediaType.length > 128 ||
      /[\r\n]/.test(file.mediaType)
    ) {
      throw new PublicationError('invalid_request', 'publication builder returned invalid generated bytes');
    }
  }
  if (!paths.has(plan.entrypoint)) {
    throw new PublicationError('invalid_request', 'publication plan does not contain its entrypoint');
  }
  if (plan.primaryPath !== undefined && !paths.has(plan.primaryPath)) {
    throw new PublicationError('invalid_request', 'publication plan does not contain its primary path');
  }
}

function blobIdentity(blob: BlobReference): string {
  return [blob.id, blob.digest, String(blob.size), blob.mediaType].join('\0');
}

/** Builds the ready marker from staged references without changing their order in the caller. */
export function publicationManifest(input: {
  publicationId: string;
  plan: PublicationPlan;
  files: readonly PublicationFile[];
  runId: string;
  conversationId?: string;
  builder: string;
  createdAt: string;
}): PublicationManifest {
  const manifest: PublicationManifest = {
    version: '1',
    publicationId: input.publicationId,
    kind: input.plan.kind,
    entrypoint: input.plan.entrypoint,
    ...(input.plan.primaryPath ? { primaryPath: input.plan.primaryPath } : {}),
    files: [...input.files].sort((left, right) => left.path.localeCompare(right.path)),
    provenance: {
      runId: input.runId,
      ...(input.conversationId ? { conversationId: input.conversationId } : {}),
      builder: input.builder,
      createdAt: input.createdAt,
    },
  };
  validatePublicationManifest(manifest);
  return manifest;
}
